# Copyright 2018 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "org.cloudfoundry.buildsystem"
name = "Cloud Foundry Build System Buildpack"
version = "1.0.0-BUILD-SNAPSHOT"

[[stacks]]
id = "packs/build"

[[metadata.dependencies]]
id      = "gradle"
name    = "Gradle"
version = "4.10.1"
uri     = "https://downloads.gradle.org/distributions/gradle-4.10.1-bin.zip"
sha256  = "e53ce3a01cf016b5d294eef20977ad4e3c13e761ac1e475f1ffad4c6141a92bd"
stacks  = [ "packs/build" ]

id      = "maven"
name    = "Apache Maven"
version = "3.5.4"
uri     = "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.tar.gz"
sha256  = "ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d"
stacks  = [ "packs/build" ]
