# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "org.cloudfoundry.buildsystem"
name = "Cloud Foundry Build System Buildpack"
version = "1.0.0-M6"

stacks = [
  { id = "io.buildpacks.stacks.bionic" },
  { id = "org.cloudfoundry.stacks.cflinuxfs3" },
]

[[metadata.dependencies]]
id      = "gradle"
name    = "Gradle"
version = "5.3"
uri     = "https://downloads.gradle.org/distributions/gradle-5.3-bin.zip"
sha256  = "bed2bdd3955be5a09ca7e0201e9d131f194f7f6c466e1795a733733ccfb09f25"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://docs.gradle.org/current/userguide/userguide.html#licenses"

[[metadata.dependencies]]
id      = "maven"
name    = "Apache Maven"
version = "3.6.0"
uri     = "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.0/apache-maven-3.6.0-bin.tar.gz"
sha256  = "6a1b346af36a1f1a491c1c1a141667c5de69b42e6611d3687df26868bc0f4637"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://www.apache.org/licenses/"

[metadata]
pre_package = "ci/build.sh"
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "buildpack.toml",
]
