---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/build-system-buildpack
    tag: latest

inputs:
- name: build-system-buildpack

outputs:
- name: artifactory

caches:
- path: go-build

run:
  path: build-system-buildpack/ci/package.sh
